Friend.create(first_name: 'Jhonata', last_name: 'Santos', email: 'jhonata.santos@gmail.com', phone: '(11)94926-4067', gender: 'male', city: 'Carapicuiba', state: 'SP', postal_code: '06329-220')
Friend.create(first_name: 'Pedro', last_name: 'Alves', email: 'pedro.alves@gmail.com', phone: '(11)94926-4068', gender: 'male', city: 'Osasco', state: 'SP', postal_code: '04129-12')
Friend.create(first_name: 'Luis', last_name: 'Santos', email: 'luis.santos@hotmail.com', phone: '(11)94926-4069', gender: 'male', city: 'Pirituba', state: 'SP', postal_code: '06133-330')
Friend.create(first_name: 'Stefany', last_name: 'Silva', email: 'stefany.silva@gmail.com', phone: '(11)94926-4070', gender: 'female', city: 'São Paulo', state: 'SP', postal_code: '07199-000')
Friend.create(first_name: 'Luzia', last_name: 'Santos', email: 'luzia.santos@hotmail.com', phone: '(11)94926-4071', gender: 'female', city: 'Brazilândia', state: 'SP', postal_code: '08178-999')
Friend.create(first_name: 'Larissa', last_name: 'Sousa', email: 'larissa.sousa@gmail.com', phone: '(11)94926-4072', gender: 'female', city: 'Barueri', state: 'SP', postal_code: '09134-280')
Friend.create(first_name: 'Lucas', last_name: 'Pietro', email: 'lucas.pietro@hotmail.com', phone: '(11)94926-4073', gender: 'male', city: 'Santana de Parnaiba', state: 'SP', postal_code: '06800-620')
Friend.create(first_name: 'Jessica', last_name: 'Soares', email: 'jessica.soares@gmail.com', phone: '(11)94926-4074', gender: 'female', city: 'Alphaville', state: 'SP', postal_code: '03298-770')
Friend.create(first_name: 'Raissa', last_name: 'Manuela', email: 'raissa.manuela@hotmail.com', phone: '(11)94926-4075', gender: 'female', city: 'Santo Amaro', state: 'SP', postal_code: '03290-888')
Friend.create(first_name: 'Leticia', last_name: 'Linhares', email: 'leticia.linhares@gmail.com', phone: '(11)94926-4076', gender: 'female', city: 'Freguesia do Ó', state: 'SP', postal_code: '01234-111')
Friend.create(first_name: 'Jhonata', last_name: 'Santos', email: 'jhonata.santos@gmail.com', phone: '(11)94926-4067', gender: 'male', city: 'Carapicuiba', state: 'SP', postal_code: '06329-220')
Friend.create(first_name: 'Pedro', last_name: 'Alves', email: 'pedro.alves@gmail.com', phone: '(11)94926-4068', gender: 'male', city: 'Osasco', state: 'SP', postal_code: '04129-12')
Friend.create(first_name: 'Luis', last_name: 'Santos', email: 'luis.santos@hotmail.com', phone: '(11)94926-4069', gender: 'male', city: 'Pirituba', state: 'SP', postal_code: '06133-330')
Friend.create(first_name: 'Stefany', last_name: 'Silva', email: 'stefany.silva@gmail.com', phone: '(11)94926-4070', gender: 'female', city: 'São Paulo', state: 'SP', postal_code: '07199-000')
Friend.create(first_name: 'Luzia', last_name: 'Santos', email: 'luzia.santos@hotmail.com', phone: '(11)94926-4071', gender: 'female', city: 'Brazilândia', state: 'SP', postal_code: '08178-999')
Friend.create(first_name: 'Larissa', last_name: 'Sousa', email: 'larissa.sousa@gmail.com', phone: '(11)94926-4072', gender: 'female', city: 'Barueri', state: 'SP', postal_code: '09134-280')
Friend.create(first_name: 'Lucas', last_name: 'Pietro', email: 'lucas.pietro@hotmail.com', phone: '(11)94926-4073', gender: 'male', city: 'Santana de Parnaiba', state: 'SP', postal_code: '06800-620')
Friend.create(first_name: 'Jessica', last_name: 'Soares', email: 'jessica.soares@gmail.com', phone: '(11)94926-4074', gender: 'female', city: 'Alphaville', state: 'SP', postal_code: '03298-770')
Friend.create(first_name: 'Raissa', last_name: 'Manuela', email: 'raissa.manuela@hotmail.com', phone: '(11)94926-4075', gender: 'female', city: 'Santo Amaro', state: 'SP', postal_code: '03290-888')
Friend.create(first_name: 'Leticia', last_name: 'Linhares', email: 'leticia.linhares@gmail.com', phone: '(11)94926-4076', gender: 'female', city: 'Freguesia do Ó', state: 'SP', postal_code: '01234-111')
Friend.create(first_name: 'Jhonata', last_name: 'Santos', email: 'jhonata.santos@gmail.com', phone: '(11)94926-4067', gender: 'male', city: 'Carapicuiba', state: 'SP', postal_code: '06329-220')
Friend.create(first_name: 'Pedro', last_name: 'Alves', email: 'pedro.alves@gmail.com', phone: '(11)94926-4068', gender: 'male', city: 'Osasco', state: 'SP', postal_code: '04129-12')
Friend.create(first_name: 'Luis', last_name: 'Santos', email: 'luis.santos@hotmail.com', phone: '(11)94926-4069', gender: 'male', city: 'Pirituba', state: 'SP', postal_code: '06133-330')
Friend.create(first_name: 'Stefany', last_name: 'Silva', email: 'stefany.silva@gmail.com', phone: '(11)94926-4070', gender: 'female', city: 'São Paulo', state: 'SP', postal_code: '07199-000')
Friend.create(first_name: 'Luzia', last_name: 'Santos', email: 'luzia.santos@hotmail.com', phone: '(11)94926-4071', gender: 'female', city: 'Brazilândia', state: 'SP', postal_code: '08178-999')
Friend.create(first_name: 'Larissa', last_name: 'Sousa', email: 'larissa.sousa@gmail.com', phone: '(11)94926-4072', gender: 'female', city: 'Barueri', state: 'SP', postal_code: '09134-280')
Friend.create(first_name: 'Lucas', last_name: 'Pietro', email: 'lucas.pietro@hotmail.com', phone: '(11)94926-4073', gender: 'male', city: 'Santana de Parnaiba', state: 'SP', postal_code: '06800-620')
Friend.create(first_name: 'Jessica', last_name: 'Soares', email: 'jessica.soares@gmail.com', phone: '(11)94926-4074', gender: 'female', city: 'Alphaville', state: 'SP', postal_code: '03298-770')
Friend.create(first_name: 'Raissa', last_name: 'Manuela', email: 'raissa.manuela@hotmail.com', phone: '(11)94926-4075', gender: 'female', city: 'Santo Amaro', state: 'SP', postal_code: '03290-888')
Friend.create(first_name: 'Leticia', last_name: 'Linhares', email: 'leticia.linhares@gmail.com', phone: '(11)94926-4076', gender: 'female', city: 'Freguesia do Ó', state: 'SP', postal_code: '01234-111')
